angular/angularfire

package.json

Also remove post install script to install third-party typings
Closes #21
Closes #20

fix(npm): include list in published module

---

src/providers/firebase_list.spec.ts
src/providers/firebase_list.ts
src/utils/firebase_list_factory.spec.ts
src/utils/firebase_list_factory.ts

chore(FirebaseList): separate FirebaseListFactory into separate module

---

src/angularfire.spec.ts
src/utils/firebase_observable.spec.ts
src/utils/firebase_observable.ts

fix(FirebaseObservable): make add() method accept any type of input

---

package.json
tools/rewrite-published-package.js

chore(package): fix path to typings for npm link

---

src/angularfire2.spec.ts
src/utils/firebase_list_factory.spec.ts
src/utils/firebase_list_factory.ts
src/utils/firebase_list_observable.spec.ts
src/utils/firebase_list_observable.ts

Accepts either a key, a snapshot, a reference, or an 
unwrapped Snapshot, to remove the item from the list.
Closes #85
Part of #41

feat(FirebaseListObservable): implement remove method

---

src/angularfire2.spec.ts
src/angularfire2.ts
src/angularfire2_worker_app.ts
src/angularfire2_worker_render.ts
tsconfig.json

chore(worker): move worker exports into separate files

---

README.md

adding a link to Angular CLI in the readme file.

link to Angular CLI to help new comers

---

README.md

Removed `&&` from npm packages install command

npm packages install command fixed

---

karma.conf.js
src/angularfire2.spec.ts
src/angularfire2.ts
src/utils/firebase_object_observable.spec.ts
src/utils/firebase_object_observable.ts

Closes #95.
Below is the interface for `FirebaseObjectObservable`:
```ts
interface FirebaseObjectObservable {
save(value:any) => Promise<void>
update(value:Object) => Promise<void>
remove() => Promise<void>
}
```

feat(object): Add set, update, and remove methods

---

package.json

Update Angular2 dep. to support Betas until RC1

---

tsconfig.json
tsconfig.publish.es5.json
tsconfig.publish.es6.json

fix(sourcemaps): change tsconfig to set correct relative path

---

docs/3-retrieving-data-as-lists.md

I always do this mistake, i am somehow happy i am not alone :)

Update Retreive -> Retrieve

---

docs/3-retrieving-data-as-lists.md

Pluralising the list names to make them a bit more intuitive.

Updating 3-retrieving-data-as-lists.md

---

docs/3-retrieving-data-as-lists.md

Fixing two older references to angular2.
Changed var to let

Updating to RC1 modules

---

docs/1-install-and-setup.md

Otherwise, firebase 3.x will be installed, which is not supported yet.

fix firebase version to 2.4.2

---

docs/1-install-and-setup.md
docs/2-retrieving-data-as-objects.md

Minor inconsistency of naming. Moreover, including an explanation for item.$value and its relevant data structure would aid learners.

docs: update Developer Guide to have consistency

---

package.json
src/angularfire2.ts

@davideast could you please review ?

Misc minor changes

---

docs/2-retrieving-data-as-objects.md
docs/3-retrieving-data-as-lists.md

The code provided for retrieving the snapshot wasn't working so I messed around and discovered what worked. See individual commit messages for specifics.

Update "Retrieving the snapshot" code snipbit in docs

---

docs/5-user-authentication.md

Fixed spelling error

---

docs/3-retrieving-data-as-lists.md

Fixed typo

---

docs/5-user-authentication.md

Add work around for cordova auth issues

Cordova case

---

docs/2-retrieving-data-as-objects.md
docs/3-retrieving-data-as-lists.md

Some small fixes that I stumbled upon when I was reading over the docs.

Very minor docs fixes

---

docs/1-install-and-setup.md

Removed comma after last value in the object passed to defaultFirebase( )

Removed comma after last value in object

---

.editorconfig
docs/1-install-and-setup.md
docs/5-user-authentication.md
package.json
src/angularfire2.spec.ts
src/angularfire2.ts
src/auth/auth.spec.ts
src/auth/auth.ts
src/auth/auth_backend.ts
src/auth/firebase_sdk_auth_backend.ts
src/database/firebase_list_factory.spec.ts
src/database/query_observable.spec.ts
src/tokens.ts
tsconfig.json
tsconfig.publish.es5.json
tsconfig.publish.es6-deprecated.json
tsconfig.publish.es6.json
typings.json

fix(providers): make AoT compile friendly

---

src/angularfire2.ts
src/database/database.ts
tsconfig.publish.es5.json
tsconfig.publish.es6.json

fix(auth): make statically analyzable x2

---

CHANGELOG.md
package.json

chore(release): Changelog

---

src/database/firebase_list_factory.ts
src/database/firebase_object_factory.ts

fix(firebase_*_factory.js): Fix calls to off()

---

docs/1-install-and-setup.md
docs/2-retrieving-data-as-objects.md

1) Corrected the Module Name.
2) Removed moduleId: module.id, which was causing Webpack errors.
3) Updated retrieve data as object page to be consistent with Install and Setup.md

Combining PR #523,#526, #528

---

docs/1-install-and-setup.md

For AngularCli tslint.json sais that quote marks has to be single :)
```
"quotemark": [
true,
"single"
]
```

tslint warning

---

docs/1-install-and-setup.md

* Fixed duplicate step numbers
* Fixed spelling error

Fix a couple grammar errors

---

src/angularfire2.ts

This will allow hmr to re-execute _getFirebase.

Allow hmr to work

---

docs/5-user-authentication.md

Update the Authentication section to make it consistent with previous sections.  Removed the ModuleId which would have caused errors, updated selector name, component name. Added logout() method for completion.

Update 5. User authentication

---

docs/1-install-and-setup.md

this.items = af.database.list('/items');
previously 
this.items = af.database.list('items');

typo at node at list of items

---

docs/install-angular-cli-windows10.md

install-angular-cli-windows10.md.
@davideast created the doc as per suggestion on issue #569

install-angular-cli-windows10.md

---

docs/3-retrieving-data-as-lists.md

Updated Tutorial to go in flow with the previous sections. export was missing, selector was not correct. removed moduleId, which could have thrown errors for new users. Component name has been corrected.

3. Retrieving data as lists

---

docs/5-user-authentication.md

chore(5-user-authentication): Fix typo

---

README.md
docs/Auth-with-Ionic2.md

- Issue number for this PR: #590
- Docs included?: Yes 
- Test units included?: N/A 
- In a clean directory, N/A
Created a walkthrough for Auth on Ionic/Cordova as per issue #590

Ionic2 angular fire2 auth

---

docs/3-retrieving-data-as-lists.md

docs(list): fix typo object → list

---

package.json

- Issue number for this PR: #730
Rxjs is in final! Getting the package.json updated and all unit tests run just fine (on my machine).
N/A

chore(build): Update and test Angular and rxjs dependencies

---

docs/4-querying-lists.md

- Issue number for this PR: #nnn (required) : none, docs only.
- Docs included?: (yes) 
- Test units included?: (no) 
- e2e tests included?: (no)
- In a clean directory, `npm install`, `npm run build`, and `npm test` run successfully? (yes)
Updating Documentation.
Querying Lists documentation added to include the query options and a short description for each option.
N/A

Querying lists options

---

src/database/firebase_list_factory.ts

- Issue number for this PR: #816 
Added error handler within FirebaseListObservable factory, which was described in #816, but other situations can be affected by this issue.

Fix #816 issue

---

docs/1-install-and-setup.md

Changed package name from angular-cli to @angular/cli

---

docs/1-install-and-setup.md

Fix headings in the documentation.

Fix headings in documentation

---

.gitignore
README.md
docs/1-install-and-setup.md
docs/2-retrieving-data-as-objects.md
docs/3-retrieving-data-as-lists.md
docs/4-querying-lists.md
docs/5-user-authentication.md
docs/Auth-with-Ionic2.md
docs/version-4-upgrade.md

Starting the work on the documentation changes for `4.0.0-rc0` #854 
Made changes to the code examples in docs 1-4 and added an upgrade guide.

4.0.0-rc0 doc changes

---

package.json

- Issue number for this PR: #854 (required)
Using the correct version number in package.json.
See #934

chore(release): Version bump

---

README.md
docs/Auth-with-Ionic3-Angular4.md

Facebook Authentication with Angular4-Ionic3 and AngularFire2
- Issue number for this PR: #914 
- Docs included?: Yes
- e2e tests included?:N/A
- In a clean directory, `npm install`, `npm run build`, and `npm test` run successfully? N/A
Authentication tutorial with Ionic 3 and Angular 4

Auth-with-Ionic3-Angular4.md

---

docs/1-install-and-setup.md

Corrected typo

---

docs/Auth-with-Ionic3-Angular4.md

- Issue number for this PR: #956
- Docs included?: yes, this is a docs change
Missing AngularFireAuthModule import at @NgModule which causes an uncaught Runtime Error when using Ionic3.
n/a

docs(auth): missing AngularFireAuthModule import

---

docs/Auth-with-Ionic2.md

- Issue number for this PR: #960 
- Docs included?: yes, this is a docs change
There were numerous errors (leftovers from < 4.0.0-rc.0) that were causing implementations of the sample code to fail compiling and/or produced Typescript errors.
These changes should bring the code up to current release compatibility.
n/a

docs: Correcting errors in methods and types

---

docs/install-angular-cli-windows10.md

Fixing a typo in one of the notes, and removing extra whitespace in a code block.
- Docs included?: yes (is a doc update)
- Test units included?: none affected 
- e2e tests included?: none affected
- In a clean directory, `npm install`, `npm run build`, and `npm test` run successfully? n/a
Fixing a typo in one of the notes, and removing extra whitespace in a code block.
n/a

Typo in docs

---

docs/3-retrieving-data-as-lists.md

doc(list.set): change example snip from `af.database` to `db`

---

CHANGELOG.md

Remove the extra fullstop
- Issue number for this PR: #nnn (required) non
- Docs included?: (yes/no; required for all API/functional changes) no
- Test units included?: (yes/no; required) no
- e2e tests included?: (yes/no; required for multi-function/multi-class changes) no
- In a clean directory, `npm install`, `npm run build`, and `npm test` run successfully? (yes/no; required) yes
Correcting a typo in the changelog
Non

Typo in changelog.md

---

package.json
src/app/firebase.app.module.ts
src/auth/auth.spec.ts
src/auth/auth.ts
src/database/firebase_list_factory.spec.ts
src/database/firebase_list_factory.ts
src/database/firebase_list_observable.spec.ts
src/database/firebase_list_observable.ts
src/database/firebase_object_observable.spec.ts
src/database/query_observable.spec.ts
src/database/query_observable.ts
tsconfig.json
tsconfig.publish.es6.json

- Issue number for this PR: #1029 
Adding `strictNullChecks` compatibility.

chore(build): Add strictNullChecks compatibility

---

README.md

Changed status to Release candidate
Updating documentation

(docs) Updated Readme status

---

docs/5-user-authentication.md

Spelling correction

---

README.md
docs/7-deploying-angularfire-to-firebase.md

- Issue number for this PR: #378  (required)
- In a clean directory, `npm install`, `npm run build`, and `npm test` run successfully? 
Updating the documentation to have deploy instructions. 
none

Update cocumentation to include deploy instructions

---

docs/Auth-with-Ionic3-Angular4.md

Hey, I'm Daniel from the Ionic Team.
I updated the Ionic (3.x) example to match our actual requirements.

docs(ionic-example): updated ionic 3.x example

---

docs/Auth-with-Ionic3-Angular4.md

#N/A [Typo Fix]

---

docs/7-deploying-angularfire-to-firebase.md

Fix typo and add some missing words

Deploying AngularFire to Firebase docs fixes

---

docs/2-retrieving-data-as-objects.md

- Issue number for this PR: #1067
NONE   - Docs included?: (no; required for all API/functional changes) 
NONE   - Test units included?: (no; required) 
NONE   - In a clean directory, `npm install`, `npm run build`, and `npm test` run successfully? (no; required)
NO
NO

Update 2-retrieving-data-as-objects.md Issue#1067

---

docs/Auth-with-Ionic3-Angular4.md

Fix Ionic build errors: see https://github.com/ionic-team/ionic-app-scripts/issues/1001

fix(): Ionic build

---

docs/4-querying-lists.md

- Issue number for this PR: #1169
- Docs included?:  yes
- Test units included?: n/a
Updating the querying docs for the new database API introduced in #1156
n/a

docs(db): updating the querying docs for the new API

---

docs/rtdb/lists.md

- Issue number for this PR: #1180
Bad example in the docs
n/a

docs(db): Fixing the list example, closes #1180

---

README.md

- Issue number for this PR: N/A
- Docs included?: yes 
Fix the link to install-and-setup.md in the README.md
N/A

Fix link to install-and-setup.md

---

docs/firestore/collections.md

- Issue number for this PR: #1200  (required)
- In a clean directory, Yes
Updating minor error in documentation, issue #1200

Fix: #1200 Use correct variable to construct item

---

docs/version-5-upgrade.md

Problem with variable 'key' in migration guide

---

docs/rtdb/lists.md

fix for snapshotChanges example

---

docs/ionic/v3.md

 Updating documentation for Ionic v3

---

docs/ionic/v3.md
docs/version-5-upgrade.md

Edit doc for sample code may cause confusion

---

src/database/interfaces.ts

- Issue number for this PR: #1214 (required)
- Docs included?: not required
- In a clean directory, `npm install`, `npm run build`, and `npm test` run successfully?: yes

fix(db): inherit generics in valueChanges interface

---

docs/rtdb/querying-lists.md

[Typo] Delete semicolon

---

docs/firestore/querying-collections.md

Typo in querying-collections

---

docs/firestore/collections.md

Only documentation fix.
Two samples in the Docs are using wrong variable names.

Fixed Firestore collections samples

---

src/firestore/collection/collection.ts

- Issue number for this PR: #1254
Added missing type as mentioned in the issue.

fix: added missing type to doc()

---

src/database/list/create-reference.ts

- Issue number for this PR: #1329  (required)

fix: update should take a Partial<T> object, fixes #1329

---

docs/firestore/collections.md

(chore): fix typo in collections.md

---

docs/auth/getting-started.md

Removed unused import from docs

---

docs/auth/getting-started.md

Correct example for creating a local variable in *ngIf
- Issue number for this PR: NA (required)
- Docs included?: NA (yes/no; required for all API/functional changes) 
- Test units included?: No(yes/no; required) 
- In a clean directory, `npm install`, `npm run build`, and `npm test` run successfully? No (yes/no; required)

docs(auth): fix error in *ngIf syntax

---

docs/firestore/documents.md

Fixing typo in documentation

---

docs/rtdb/objects.md

Fix docs/rtdb/objects.md to reflect 5.0.0 changes and deprecations

---

docs/storage/storage.md

https://github.com/angular/angularfire2/issues/1501

docs(): fix bug in storage downloading files example

---

docs/firestore/documents.md

Minor grammar fix.

---

docs/firestore/collections.md

docs(firestore): Update add example to use set

---

src/firestore/firestore.spec.ts
src/firestore/firestore.ts
tools/build.js
yarn.lock

Workarounds for https://github.com/firebase/firebase-js-sdk/issues/605 and https://github.com/firebase/firebase-js-sdk/issues/608

fix(afs): workarounds for firebase-js-sdk #605 and #608

---

src/storage/observable/fromTask.ts
src/storage/ref.ts
src/storage/storage.spec.ts
src/storage/storage.ts
src/storage/task.ts

Updates storage to rxjs pipeable operators

(storage) Update to rxjs pipeable operators

---

src/auth/auth.spec.ts
src/auth/auth.ts

Updates auth to rxjs pipeable operators

(auth) Update to rxjs pipeable operators

---

CHANGELOG.md

chore(): Added two extra points to the changelog

---

docs/firestore/querying-collections.md

Fixing legacy documentation around querying references.

docs(): Fixing legacy documentation around querying references

---

src/firestore/collection/changes.ts

fix(afs): Gracefully handle duplicate emissions on modified/deleted

---

src/storage/ref.ts

Fix for the timers that start in Storage RequestInfo.

fix(storage): fix for zone issues on storage

---

CHANGELOG.md
package.json

chore(release): rc12

---

CHANGELOG.md

- Issue number for this PR: none
- Docs included?: yes 
- Test units included?: ni
This pull request fixes a typo in `CHANGELOG.md`.

docs(): minor typo fix

---

src/firestore/firestore.ts

* `catchError` wasn't cutting it, switching to try/catch
* Don't try to enable persistence in Universal

fix(afs): Better handle enablePersistence failures, esp. for Universal

---

tools/build.js

* Externals and plugins moved, this addresses many warnings
* Silence the "this is undefined" warning, as it's produced by Typescript

fix(build): Fixed more rollup changes and silenced warnings

---

docs/auth/getting-started.md

This is done do that we don't include all of firebase library, and the final bundle is smaller.

Include auth from firebase/app, instead of firebase.

---

docs/functions/functions.md

docs: fix typo

---

docs/rtdb/lists.md

Update documentation to fix typo. `thru --> through`

Update lists.md to fix typo

---

docs/messaging/messaging.md

typo caused by copying from cloud storage

---

src/firestore/firestore.ts

No longer pull in the depreciated timestampsInSnapshots setting

---

CHANGELOG.md
package.json

chore(): Changelog for 5.1.1 and 5.1.2

---

package.json
src/firestore/collection/collection.spec.ts
src/firestore/document/document.spec.ts
src/firestore/firestore.spec.ts
yarn.lock

* App.delete is still causing troubles
* Bump to allow Firebase v6

Fix flaky tests & allow use with Firebase v6

---

src/storage/ref.ts

Found a typo.  You may choose to leave the old method name in place for a bit.  This pull request does.

Type in updateMetadata method.

---

docs/deploy/getting-started.md
src/schematics/ng-add.ts

- Issue number for this PR: None
- Docs included?: Yes
- Test units included?: Not applicable
Addressing comments by @jhuleatt

refactor: update documentation & improve error messages

---

package.json
yarn.lock

- Issue number for this PR: #2082
Support zone.js ^0.9.0 for Angular version 8
N/A

build: support zone.js ^0.9.0 for Angular version 8

---

docs/functions/functions.md

docs: Update functions.md with suggested changes

---

package.json
tools/build.js

As suggested in
https://github.com/angular/angularfire/issues/1799#issuecomment-423128066
After applying the fixes I was able to run the build on windows and generate a package

fix(build): Make the build work on windows

---

package.json

chore(build): fix the wrapper:build command

---

CHANGELOG.md
tools/test.sh

chore(release): version 5.2.2 changelog entry

---

src/auth/auth.spec.ts
src/functions/functions.spec.ts
src/performance/performance.spec.ts

chore(): Fix minor typos in test descriptions

---

docs/install-and-setup.md

Updated install and setup doc to include performance monitoring

added PerformanceModule

---

src/remote-config/remote-config.ts

fix(rc): Need to ensureInitialized()

---

src/storage/storage.ts

fix(storage): fix `AngularFireStorage` erroneous error message

---

docs/install-and-setup.md

Added missing commas to NgModule

---

docs/ionic/cli.md

The package for the new ionic cli is `@ionic/cli`
Source:
https://ionicframework.com/blog/a-new-package-for-the-cli/
- Docs included?: yes (yes/no; required for all API/functional changes) 
- In a clean directory, `yarn install`, `yarn test` run successfully? yes (yes/no; required)

docs: Update cli.md

---

README.md
docs/ionic/authentication.md
docs/messaging/messaging.md
docs/remote-config/getting-started.md
docs/rtdb/querying-lists.md

- Issue number for this PR: Closes #2176. Closes #2156. Closes #2248. Closes #2264.
This PR combines a number of open documentation PRs which have CLA issues, haven't responded to review feedback, are pending review for many months, etc. It also adds some additional documentation cleanup for 
- Ionic Auth
- AngularFireMessaging
- AngularFireRemoteConfig
- RTDB Querying Lists
- README
It also updates the AngularFireMessaging docs to point to the related issue in the Angular repo (asking them to thumbs up the issue) rather than asking them to create new duplicate issues.

docs: fix typos and clarify documentation

---

src/storage/interfaces.ts
src/storage/ref.ts

- Docs included?: no (yes/no; required for all API/functional changes) 
For #2268 listAll function doc, without test file.

add storage list all function

---

src/firestore/document/document.spec.ts
src/storage/ref.ts

Looks like some tests got broken

chore(tests): Fix broken tests

---

src/schematics/ng-add-common.ts

* Refer to the correct object
- Issue number for this PR: #2479
Fixed firebase to be added to dependencies when running `ng add @angular/fire`

fix(schematics): firebase does not added to dependencies (#2479)

---

docs/install-and-setup.md

docs(quickstart): ng add @angular/fire

---

docs/firestore/collections.md

- Issue number for this PR: #2487
- Docs included?: No
Fix typo `metdata` to `metadata`
No sample

Update collections.md Typo

---

docs/install-and-setup.md

Fix docs on how to get firebase config in console

---

CHANGELOG.md
docs/performance/getting-started.md
src/database/list/create-reference.ts
src/firestore/firestore.ts
src/schematics/deploy/actions.ts

* Fixed a merge conflict in the deploy script
* CRUD operations (database/firestore) should be in ngZone

6.0.1 release

---

CHANGELOG.md
package.json
yarn.lock

Version bumps to support ng10

---

src/auth/auth.ts

Workaround for getRedirectResult not working

---

package.json
tools/build.sh

chore(release): skip git tag on npm version

---

CHANGELOG.md

chore(release): 6.0.4 changelog entry

---

.github/workflows/test.yml
tools/run-typings-test.js

chore(test): action cache

---

src/storage/observable/fromTask.ts

fix(storage): error state not represent in UploadTaskSnapshot

---

src/analytics/screen-tracking.service.ts

fix(analytics): screen tracking will no longer fail on broken routes

---

README.md
docs/emulators/emulators.md

- Issue number for this PR:  #2615, #2183. Also references #2663
Add Emulator docs for both 6.1.0 and 6.0.0 versions.

Add Configuring Local Emulator Suite

---

.github/workflows/test.yml
.npmignore
package.json
tools/build.sh
yarn.lock

Optimize caching

---

README.md

docs(root): Fixed typo in readme

---

docs/version-7-upgrade.md

docs(upgrade): Fix typo initalizeApp -> initializeApp

---

docs/auth/getting-started.md

Fix for `/compat` missing from firebase import

Update getting-started.md: `/compat` missing from firebase import

---

src/schematics/update/v7/index.ts

fix(schematics): ng upgrade when e2e is present, fixes #2924

---

samples/advanced/yarn.lock
samples/compat/package.json
samples/compat/yarn.lock
samples/modular/package.json
samples/modular/yarn.lock
yarn.lock

Update deps, fixes compat issues #2932

---

samples/advanced/src/app/app.browser.module.ts
samples/advanced/src/app/app.module.ts
samples/advanced/src/app/app.server.module.ts
samples/compat/src/app/app.browser.module.ts
samples/compat/src/app/app.module.ts
samples/compat/src/app/app.server.module.ts
samples/compat/src/environments/environment.ts
samples/compat/src/main.ts
samples/modular/server.ts
samples/modular/src/app/app.browser.module.ts
samples/modular/src/app/app.module.ts

Misc cleanup

---

package.json
src/package.json
src/schematics/add/index.ts
src/schematics/common.ts
src/schematics/setup/prompts.ts
src/schematics/setup/ssr.ts
src/schematics/setup/static.ts
src/schematics/utils.ts
yarn.lock

* Add missing dependencies
* Fixed the cyclic dep that was halting ng add
* Simplified ng-add

Missing deps, fixed ng add bug

---

CHANGELOG.md
README.md

Dropping ng8 & adding ng13 to readme

---

src/core.ts

Defensively catching on isSupported calls

---

.github/workflows/test.yml

Add firebase-tools 10 to test matrix

---

CONTRIBUTING.md

fix(common): url link format from http to https updated

---

.github/workflows/test.yml
CHANGELOG.md
README.md
package.json
src/auth/firebase.ts
src/database/firebase.ts
src/functions/firebase.ts
src/package.json
yarn.lock

* Bump firebase again
* Contribute windows node 14 needed a java bump too
* Add readme for ng 14
* Drop IE references in readme
* Add changelog

Bump firebase again

---

.github/workflows/test.yml
src/package.json
src/schematics/deploy/actions.ts

* Update github actions
* Fix semver check for ng-deploy
* Drop file-loader, fixes #3324

Quick fixes

---

src/schematics/ng-add.jasmine.ts
src/schematics/setup/index.ts

These should default to prod now thinking about it

Default ng-deploy to production

---

samples/advanced/test.js
samples/modular/test.js

Update samples to replace the chholland-test project (my personal test project) with the angularfire sample project used in the other samples in this repo. Must have got in there in an accidental copy-paste when the samples were added in https://github.com/angular/angularfire/pull/2898 ?

update sample project

---

package-lock.json
package.json

19.2.0 release
