angular/angularfire

.gitignore
README.md
src/angularfire.spec.ts
src/angularfire.ts

@jeffbcross 
Addresses #24. 
You can now do:
```js
providers: [defaultFirebase('https://myfirebase.firebaseio.com/')]
```
There's even tests.

chore(providers): shortcut for configuring DEFAULT_FIREBASE provider

---

src/angularfire2.spec.ts
src/angularfire2.ts
src/providers/auth.spec.ts
src/providers/auth.ts
src/providers/auth_backend.ts
src/providers/firebase_sdk_auth_backend.ts
src/providers/web_workers/shared/channels.ts
src/providers/web_workers/ui/auth.ts
src/providers/web_workers/worker/auth.ts

In lieu of official WebWorker support in the Firebase SDK, we're proxying auth requests to the UI and then replaying them using custom token on the worker.

feat(auth): Add WebWorker authentication support

---

src/angularfire2.spec.ts
src/utils/firebase_list_factory.spec.ts
src/utils/firebase_list_factory.ts
src/utils/firebase_object_factory.spec.ts

Previously, a new array would be emitted for each
child_added event for a ref, even data that was
already available when the list observable was subscribed.
This change waits until the initial set of data has been
loaded by Firebase before emitting the initial array.
Closes #52

DUPLICATE fix(FirebaseListFactory): emit initial data only once

---

.gitignore
CONTRIBUTOR.md
docs/firebase.json
package.json
src/angularfire2.ts

This PR adds an npm script to generate API docs, and adds firebase hosting configuration to publish API docs to angular-fire-2.firebaseapp.com (soon to be angularfire2.com). 
The API docs are published to /api, and the root of the domain automatically redirects to /api for now, until a proper landing page is implemented. 
The docs are built using my fork of [typedoc](https://github.com/sebastian-lenz/typedoc)
Closes #88

Auto api docs

---

src/angularfire2.spec.ts
src/angularfire2.ts

feat(AngularFire): support absolute urls in list() and object()

---

src/angularfire2_worker_render.ts

Until https://github.com/angular/angular/issues/7420 is implemented users need to manually inject this service and start it so it should be public.

fix(worker): Add export for MessageBasedFirebaseAuth to angularfire2/worker_render path

---

src/utils/firebase_list_observable.spec.ts
src/utils/firebase_list_observable.ts

Closes #41. 
Thoughts @jeffbcross and @TylerEich?
Changelist:
- Renamed `add` to `push` (breaking)
- Added `update`
- Modified `remove`. If no key param provided the entire list will remove
Examples below:
```ts
export class MyApp {
constructor(private _af: AngularFire) {
const db = this._af.database;
const pushRef = db.list('/items').push({ name: 'item 1' });
const changedPromise = this._af.database.list('/items').update(pushRef, { changed: true});
const removedPromise = db.list('/items').remove();
changedPromise.then(err => console.log(err || 'No errors!'));
removedPromise.then(err => console.log(err || 'No errors!'));
}
}
```

feat(list): Add methods to FirebaseListObservable

---

docs/1-install-and-setup.md

Use `item.$value` otherwise it will print `[object Object]`
Hey @davideast i hope these small PRs are ok, its just that i am finding them as i go along the docs.

1-install-and-setup.md

---

docs/2-retrieving-data-as-objects.md

- "item.name" is not an observable so we can't use the async pipe on it.
- use the safe navigation operator to access the name property of the retrieved object.

Fix data binding expression in the example

---

src/angularfire2.ts
src/providers/auth.spec.ts
src/providers/auth.ts
src/tokens.ts

When using AngularFire in non-browser environments, such as Ionic,
subscribing to the AngularFireAuth service would cause an error to
be thrown. This was because getRedirectResult() is always called
at the beginning of the auth observable, to determine if the page
is being loaded after a redirect-based oAuth flow. However, calling
this method is not supported if location.protocol is not http or https.
In the case of Ionic, the protocol is file:.
This change adds a check before calling getRedirectResult to make sure
the protocol is http or https.
BREAKING CHANGE:
The AngularFireAuth class has changed the order of its constructor arguments.
Since this is usually instantiated automatically via dependency injection,
it shouldn't affect common usage of the library. However, if manually …

fix(auth): check protocol before calling getRedirectResult

---

docs/1-install-and-setup.md
docs/2-retrieving-data-as-objects.md

Add prerequisites for clean install.

---

docs/1-install-and-setup.md

This will update the current paths to match the `angular-cli-build.js` file built by the latest Angular CLI.

docs: update npm vendor files

---

docs/api-reference.md

under: Subscribing to Authentication State
`*ng-if` was replaced with `*ngIf` (the correct Angular2 syntax)
an extra usage was added to make it more fluid for components with AngularFire already, instead of a new component for FirebaseAuth. Fits in better with https://github.com/angular/angularfire2/blob/master/docs/5-user-authentication.md
Finally, not sure if `@Inject(FirebaseAuth)` is necessary as it seems to work without it on my machine, but left it in the original usage (would probably also have to include an import statement for it in the original usage; I'll leave that to the original author.

update api-reference.md (authentication usage)

---

docs/1-install-and-setup.md

This minor update instructs users to install the firebase3 typings file into `typings.json` instead of into `tsconfig.js`. I believe that this method is better because some projects use the `"excludes"` property in tsconfig (I encountered this in an Ionic v2 setup), which is mutually exclusive to the `"files"` property. 
> The "files" property cannot be used in conjunction with the "exclude" property <sup>[1](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html)</sup> 
If users do not know this, they can inadvertently begin including files that they had been meaning to exclude. Otherwise they might think they have to refactor their globbing pattern to use with `"files"` instead of `"exclude"`, which isn't necessary if the typings are left out of tsconfig. 
I shared this …

Update typings installation instructions.

---

docs/1-install-and-setup.md

It was probably a typo to place ngFor directive in "ul" tag rather than "ul" tag.
Most documents I've read with this syntax (including here https://github.com/angular/angularfire2 ) have placed this directive in the "li" tag.
Also, it would be prettier to create a single list and add multiple items to that list rather than have multiple lists with a single item.

Moved ngFor directive to <li> rather than <ul>

---

docs/2-retrieving-data-as-objects.md
docs/3-retrieving-data-as-lists.md

update list query syntax
Fixes #341

docs(binding): update syntax for object and list binding

---

src/auth/auth.spec.ts
src/auth/firebase_sdk_auth_backend.ts
src/utils.ts
test/e2e/auth/firebase_auth_example.ts
tsconfig.json

fix(auth): add scheduler to schedule onAuth events through Angular zone

---

package.json
tsconfig.publish.es5.json

We can use tilde for the project's dependencies and respectively for the project's `peerDependencies` once published. Verified by @jeffbcross and me [here](https://github.com/angular/mobile-toolkit/pull/79).
The PR has also a fix for the main file that contains references to all the ambient type definitions installed with typings 1.3.2.

chore(peerDependencies): use tilde for matching peerDependencies

---

docs/5-user-authentication.md

* Fix the syntax to fetch the correct authencation response.
* With the current syntax an exception is thrown: "cannot read property null of uid"

Fix the syntax for an example in user-authentication docs.

---

docs/3-retrieving-data-as-lists.md

Update 'Observable' and 'FirebaseObjectObservable' to 'FirebaseListObservable' where needed.
Update component methods to be prefixed by 'Item'. This prevents collisions, and improves readability, in situations where the previous step's example is combined with this one.
Update field being updated from size to text. This allows the updates to be immediately observable without any additional code, since item.size was not being displayed.

docs(3-retrieving-data-as-lists.md): clarity and FirebaseListObservable correction

---

package.json
src/angularfire2.ts
src/auth/auth_backend.ts

Correcting the auth type used in `AngularFireModule.initializeApp(config: FirebaseAppConfig, auth: AuthConfiguration)`.

fix(auth): Auth config for initializeApp

---

README.md

RC5 support is available in the next tag. Waiting on more usage before replacing the main release.
```bash
npm install firebase angularfire2@next --save
```

chore(docs): Update README for next releases

---

CONTRIBUTOR.md

Devs may need to run `typings install` before npm run build.

Add a note about `typings install`

---

src/auth/auth_backend.ts
src/database/firebase_list_factory.spec.ts
src/database/firebase_object_factory.spec.ts
src/interfaces.ts
src/utils.ts

Closes` #300. Also closes #464.
Exposes the `DataSnapshot#exists` function to the `AFUnwrappedSnapshot`.
```ts
af.database.object('myKey').subscribe((obj) => {
if (obj.$exists()) {
// object exists
} else {
// object does not exist
}
});
```

feat(utils): Add $exists method to AFUnwrappedSnapshot

---

docs/5-user-authentication.md

Corrected signature in docs for overriding user auth with `AuthMethods.Password`
See #336.

fix(docs): Fix user auth code example that throws an exception

---

docs/1-install-and-setup.md

Include troubleshooting steps for "Cannot find namespace 'firebase'"
Update versions and syntax to match latest angular-cli output.
@davideast

Update readme instructions

---

docs/1-install-and-setup.md

Updated troubleshooting section to notify the "require" error, while invoking ng serve and 
modified pre-requisites section to update the order in which angular-cli version is checked.

Update Pre-requisities and troubleshooting section

---

docs/1-install-and-setup.md

Just noticed. minor change, but important. changed the selector in "app.component.ts" to match the selector in the index.html. 
They were reversely named(<app-root> vs <root-app>).

Updated selector name in app.component.ts

---

docs/1-install-and-setup.md

The latest cli build (14) is based on webpack in the master branch so you don't need the `@webpack` anymore.

update installation guide to latest cli version

---

docs/5-user-authentication.md

There is no reference to the `logout()` function in the documentation file **5-user-authentication.md**.
Would have liked to add this to the **api-reference.md** file too, but someone has already submitted an extensive updated PR for the same.

docs(authentication): Add logout() method to guide.

---

docs/1-install-and-setup.md

Typescript 2 is now out and on the release channel so no need to mention that they have to install Typescript 2.0.3

Remove mentions to specifically install Typescript2

---

docs/4-querying-lists.md

Updated the Query list Section to bring in consistency across other pages. Removed ModuleId to avoid errors. updated Selector, Component name. Added a sample data set at the end from completion point of view.

Updated 4. Querying lists

---

README.md

Simple fix of broken link in README.md broken after rename of CONTRIBUTOR.md to CONTRIBUTING.md

docs(contributing): Fixed link to CONTRIBUTING renamed at commit ea80969

---

rollup.publish.config.js

- Issue number for this PR: #534  #543 
- e2e tests included?: yes
This PR fixes issue #543. The actual code change was written by @meDavid from PR #534 but he hasn't yet signed the CLA and my project needs this PR to be merged for deployment. 
In the rollup script 'angularFire2.umd.js' is used, where in the package.json 'angularfire2.umd.js' was used, causing for loading problems on linux based systems (Ubuntu in this case)

Updated package.json to use the correct casing for the 'main' entrypoint

---

docs/5-user-authentication.md

- Issue number for this PR: https://github.com/angular/angularfire2/issues/627
- Test units included?: no, no code change
- e2e tests included?: no, no code change
On first reading the Auth docs while doing the RC.4 to 2.1.0 upgrade and coming from angularfire2 beta.2 to beta.5, it was confusing if there was some new way to getting AuthProviders and AuthMethods. I was wondering if these come from the AngularFireModule now or if they came from a service or something. It would have saved me a lot of confusion to just specify that that they are still imported from angularfire2 like before. I.e. `import { AngularFireModule, AuthProviders, AuthMethods } from 'angularfire2';`
Also …

docs(auth): add imports for AuthProviders and AuthMethods

---

ISSUE_TEMPLATE.md

Run the linter and test suite
==============================
n/a
Add tests (if applicable)
==============================
n/a
Sign our CLA
==============================
Done
- Test units included?: n/a
- e2e tests included?: n/a
Updating issue template to encourage better minimal repros and due diligence.
n/a

docs: Improve wording of issue template

---

package.json

- Issue number for this PR: #217
Just a little fix to permit any windows user to run `npm test` normally.

Fix npm test command for windows

---

docs/api-reference.md

Added AngulaFireAuth API's as per issue #93. Please review and let me know, if any changes are needed.

AngularFireAuth API's

---

src/auth/auth.ts
src/auth/firebase_sdk_auth_backend.ts
src/database/firebase_list_factory.ts
src/database/query_observable.ts
src/utils.ts
src/worker/auth/worker/auth.ts

- Issue number for this PR: #704
- In a clean directory, `npm install`, `npm run build`, and `npm test` run successfully? no
After following the steps in the contribution guide, the generated `test-root.umd.js` bundle was empty - apart from the boilerplate. This could have something to do with Windows being my OS. Hopefully, Travis will run the tests for me.
This PR includes a refactor to rename a method that was [considered to be misleading](https://github.com/angular/angularfire2/issues/704#issuecomment-264202189) and a fix to allow the `equalTo`, `startAt` and `endAt` options for list queries to be `null` - as the current AngularFire2 behaviour differs from that of the underlying SDK (see the …

fix(database): allow null values for equalTo, etc.

---

karma.conf.js
package.json
src/database/firebase_list_factory.spec.ts
src/database/firebase_list_factory.ts
src/utils.ts

- Issue number for this PR: #574 (required)
- Docs included?: Lots of comments 
- e2e tests included?: n/a
Fixes issue with FirebaseListFactory emitting items individually rather than the initial data set.
```ts
@Component({
})
class SampleComponent implements NgOnInit {
constructor(private _af: AngularFire) {}
ngOnInit() {
this.af.list('items').subscribe(list => {
// Full list!
console.log(list);
});
}
}
```

fix(list): Work around Firebase SDK sync quirk

---

docs/api-reference.md

removed line break at 271 which was breaking syntax highlighting for that code block

docs(api-reference) typo

---

docs/5-user-authentication.md
docs/api-reference.md
src/auth/auth.ts
src/auth/auth_backend.ts
src/auth/firebase_sdk_auth_backend.ts

- Issue number for this PR: #583 (required)
- Change the `AuthBackend.unauth()` method to return the value of the `_authBackend.unauth` call
- Change the `FirebaseSdkAuthBackend.unauth()` method to return a promise instead of `void` to match the [API](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#signOut) as suggested in #583
```js
this.auth$.logout().then(() => {
console.log('Logged out!');
});
```

Change logout methods to return a promise

---

package.json
src/angularfire2.ts
src/auth/firebase_sdk_auth_backend.ts

- Issue number for this PR: #728 
Fix for #728. The solution was to remove the web worker parameter as we do not support web workers with auth at the moment.
Verified no errors when building locally with @StephenFluin's [aot-repo](https://github.com/StephenFluin/aot-repro).
cc: @hansl and @chuckjaz

fix(aot): Remove AuthBackend param for AOT support

---

docs/1-install-and-setup.md
docs/5-user-authentication.md
docs/Auth-with-Ionic2.md
src/interfaces.ts

- Issue number for this PR: #742  (required)
- e2e tests included?:  N/A
Adding `messagingSenderId` to `FirebaseAppConfig` so Firebase Cloud Messaging for the web can be used from the default app instance.
```ts
AngularFireModule.initializeApp({
apiKey: "xxxx",
authDomain: "xxxx.firebaseapp.com",
databaseURL: "https://xxxx.firebaseio.com",
storageBucket: "xxxxx.appspot.com",
messagingSenderId: "xxxxxx" 
})
```

fix(config): Add messagingSenderId to FirebaseAppConfig

---

README.md

Reverts Firebase version to 3.4.0 to work around #576.

Update Plunker link to a working reference

---

package.json
tools/rewrite-published-package.js

- Issue number for this PR: #707, #747 
In post build all dependencies (Firebase, Angular, rxjs) are set as `peerDeependencies` to avoid version mismatch errors.

chore(build): Set Firebase, Angular, and rxjs as peerDependencies

---

docs/1-install-and-setup.md
docs/5-user-authentication.md
src/angularfire2.spec.ts
src/angularfire2.ts
src/database/firebase_list_factory.spec.ts
src/tokens.ts

- Issue number for this PR: #557 
Allow `AngularFireModule`'s `initializeApp` method to pass in a custom `firebase.app.App` name.
```ts
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { AppComponent } from './app.component';
import { AngularFireModule } from 'angularfire2';
// Must export the config
export const firebaseConfig = {
apiKey: '<your-key>',
authDomain: '<your-project-authdomain>',
databaseURL: '<your-database-URL>',
storageBucket: '<your-storage-bucket>',
messagingSenderId: '<your-messaging-sender-id>'
};
const authConfig = {
provider: …
```

feat(module): Add a custom FirebaseApp name

---

src/angularfire2.ts
src/auth/auth.ts
src/database/database.ts

- Issue number for this PR: #754 (required)
Awhile back we renamed `FirebaseAuth` to `AngularFireAuth` and `FirebaseDatabase` to `AngularFireDatabase`.
This does not affect most developers as they inject everything through the `AngularFire` service. However, you can inject them individually so we decided to keep the old names around for a bit by extending from the new classes.
Enough time has passed to push people to the new providers, and it's a small use case anyway.
However, if you see ERROR: FirebaseAuth not defined or ERROR: FirebaseDatabase not defined then switch to the new names: AngularFireAuth and …

chore(api): Remove old database and auth providers

---

docs/Auth-with-Ionic2.md

- Issue number for this PR: #nnn (required) *none* it's a docs change
- Docs included?: (yes/no; required for all API/functional changes)  *it is docs*
- Test units included?: (yes/no; required) *n/a*
- e2e tests included?: (yes/no; required for multi-function/multi-class changes) *n/a*
- In a clean directory, `npm install`, `npm run build`, and `npm test` run successfully? (yes/no; required) *n/a*
FirebaseAuth didn't exist for the latest dependencies I could find. AngularFireAuth works though
"angularfire2": "^2.0.0-beta.7",
"firebase": "^3.6.6",
"ionic-angular": "2.0.0-rc.5",
"ionic-native": "2.2.11",

FirebaseAuth didn't exist for me. It's AngularFireAuth

---

src/database/firebase_object_factory.spec.ts
src/database/firebase_object_observable.spec.ts
src/utils.ts

- Issue number for this PR: #302
Exact same pull request as #535, addresses rebase merge conflicts. All credit for original fix goes to @meDavid.

fix(utils): Make object $key and $exists properties non-enumerable

---

src/database/firebase_list_factory.spec.ts
src/database/firebase_list_factory.ts

To reproduce bug:
Create a `FirebaseListObservable` on an **existing** non-empty reference:
```
{
index1: true,
index2: true,
index3: true
}
```
Remove the last child in the list. The `FirebaseListObservable` emits the correct list with the last item removed.
Then add the same item (i.e. using the same key) back to the list. Because `hasInitialLoad` is not checked in the `child_added` event handler, and because `child.key === lastKey`, the function returns prematurely and `onChildAdded` is not called. As a result the `FirebaseListObservable` emits an unchanged list, without appending the item as expected.
Sorry I haven't been able to create a unit test to demonstrate the bug. I hope the description is clear enough!

Fixing a bug in child_added event handler

---

src/database/firebase_list_factory.spec.ts
src/database/firebase_list_factory.ts

Store either unwrapped snapshots or preserved snapshots; don't store
preserved snapshots and call utils.unwrapMapFn when emitting.
Closes #791
- Issue number for this PR: #791
- Test units included?: yes 
Fixes #791. The `FirebaseListObservable`'s internal array now stores either snapshots or unwrapped snapshots depending upon the `preserveSnapshot` option. Between emissions, unchanged elements now refer to the same object instances - which should see significant performance improvements when using Angular's `OnPush` change detection strategy.

fix(database): store unwrapped snapshots

---

src/database/query_observable.spec.ts
src/database/query_observable.ts
src/test-root.ts

- Issue number for this PR: #389 and #770
- Test units included?: yes 
This PR adds an [`auditTime(0)`](http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-auditTime) operator to the composed query observable. That means the query is not emitted immediately, but is emitted in the event loop - so if there are changes made to multiple subjects, those changes don't result in the emission of multiple queries. See [this comment](https://github.com/angular/angularfire2/issues/770#issuecomment-272402754).
I've made the auditing optional (it defaults to `true`) so that the `observeQuery` tests could remain synchronous and simple. …

feat(database): adds auditTime for queries

---

src/database/firebase_list_factory.spec.ts
src/database/firebase_list_factory.ts

Closes #819
- Issue number for this PR: #819
This PR simplifies the list implementation so that only the reducers associated with the `child_added/remove/changed` events manipulate the list's internal array. The `value` event is only used to determine when the initial load has been done.
The `on('value')` and `on('child_added', ...)` calls are made within the same turn through the event loop, so only a single copy of the initial content is retrieved.
The comments made in the commit that introduced this retrieve-the-initial-content-twice behaviour mention SDK quirks and nuances. By using only the `child_XXX` events and by …

fix(database): retrieve initial list content once

---

docs/4-querying-lists.md
src/database/firebase_list_factory.spec.ts
src/database/firebase_list_factory.ts

- Issue number for this PR: #362
This PR introduces support for the optional `key` parameter that can be passed to the SDK's `startAt` method. According to the SDK documentation, the parameter is [*"allowed if ordering by child, value, or priority"*](https://firebase.google.com/docs/reference/js/firebase.database.Reference#startAt).
There was some discussion in the linked (and closed) issue regarding the `key` parameter only being supported and useful when ordering by priority, but the documentation suggests that it is also supported - by `startAt` - when ordering by child and value. Indeed, were it not to be supported, it …

feat(database): support the optional startAt key

---

src/database/firebase_list_factory.spec.ts
src/database/firebase_list_factory.ts

- Issue number for this PR: #830
This PR adds a failing test and replaces `mergeMap` with `switchMap` - which then sees the test pass.

fix(database): use switchMap when a list's query changes

---

docs/4-querying-lists.md
src/database/firebase_list_factory.spec.ts
src/database/firebase_list_factory.ts

Closes #837
- Issue number for this PR: #837
This PR adds support for the optional `key` parameter for `equalTo` and `endAt`, as the SDK documentation now states the the optional parameter is supported for those methods, too. See linked issue for documentation links and references, etc.

feat(database): support optional endAt/equalTo key

---

package.json
src/angularfire2.spec.ts
src/angularfire2.ts
src/auth/auth.spec.ts
src/auth/auth.ts
src/auth/auth_backend.spec.ts
src/auth/auth_backend.ts
src/auth/firebase_sdk_auth_backend.ts
src/database/database.ts
src/database/firebase_list_factory.spec.ts
src/database/firebase_list_factory.ts
src/database/firebase_list_observable.spec.ts
src/database/firebase_list_observable.ts
src/database/firebase_object_factory.spec.ts
src/database/firebase_object_factory.ts
src/database/firebase_object_observable.spec.ts
src/database/firebase_object_observable.ts
src/interfaces.ts
src/utils.ts
src/worker/auth/worker/auth.ts

- Issue number for this PR: #851 (required)
The Firebase SDK allows you to "naked import" a feature so module bundlers can import only what they need in the build.
To start, we should switch all features to use these imports. A following PR needs to break out each feature into an @NgModule.

chore(imports): Use naked imports for features

---

src/database/firebase_list_factory.spec.ts
src/database/query_observable.spec.ts

- Issue number for this PR: #875
This PR fixes TypeScript errors that are effected by `@types/jasmine` versions 2.5.46 and later - the declarations of which have replaced many uses of `any` with specific types.

fix(database): Fix test TypeScript errors

---

src/app/package.json
src/auth/package.json
src/database/package.json
tools/rewrite-published-package.js

- Issue number for this PR: #880
This PR adds `package.json` files so that deep path imports will direct bundlers that do not recognise the `module` entry point to the UMD bundle.
This is the same approach taken with the Angular packages. There is more information in the referenced issue.
The PR also extends the `tools/rewrite-published-package.js` build script so that the `package.json` files are copied to the `dist` directory.

fix(build): Add package.json files for deep paths

---

docs/Auth-with-Ionic2.md

Looks like there was an extra (accidental?) Markdown H4 alongside italics on line 246. Updated to reflect the way the rest of the doc is formatted with "this should" statements.

Remove extra `####` from docs

---

package.json
src/angularfire2.ts
src/app/firebase.app.module.ts
src/auth.ts
src/auth/auth.module.ts
src/auth/auth.spec.ts
src/auth/index.ts
src/database.ts
src/database/database.module.ts
src/database/database.ts
src/database/firebase_list_factory.spec.ts
src/database/firebase_list_observable.spec.ts
src/database/firebase_object_factory.spec.ts
src/database/firebase_object_factory.ts
src/database/firebase_object_observable.spec.ts
src/database/index.ts
src/database/query_observable.spec.ts
src/interfaces.ts
src/tokens.ts
tsconfig.json
tsconfig.publish.es6.json

- Issue number for this PR: #843  (required)
Switching out `OpaqueToken` for `InjectionToken` for the Angular 4 upgrade. Although `OpaqueToken` must be named in `angularfire2.ts` because it seems `InjectionToken` still uses it under the hood.

chore(upgrade): Upgrade to Angular 4

---

src/auth/auth.ts
src/database/database.ts
src/database/firebase_list_factory.spec.ts
src/database/firebase_list_factory.ts
src/database/firebase_object_factory.spec.ts
src/database/firebase_object_factory.ts
src/utils.ts

Closes #907
- Issue number for this PR: #907
Observable factories now receive `DataReference` parameters and cannot be passed path strings. See #907.

chore(refactor): Removed factory path params

---

src/database/database.ts

Exposing `app.database()` as `AngularFireDatabase.database` to be consistent with the `AngularFireAuth` API.

Adding AngularFireDatabase.database

---

docs/version-4-upgrade.md

need to call the import something, right?
- In a clean directory, `npm install`, `npm run build`, and `npm test` run successfully? with changes, yes
Fixing a typo, missing the identifier for importing `*` from `firebase/app`

docs: Fix missing identifier

---

docs/1-install-and-setup.md

Copied some material from https://github.com/angular/angularfire2/issues/854 into this doc

Add information about individual @NgModules

---

docs/1-install-and-setup.md

- Docs included?: yes, this is a doc change
I'm adding this change to the initial setup of AngularFire2 whereby the `environment.ts` file is used for config instead of putting it in the app.module.ts file itself.
This change brings the setup docs into parity with Upgrade Guide where the environment.ts file is referenced but never actually explained.
n/a

docs: updating config import method (environment.ts)

---

CHANGELOG.md

- Issue number for this PR: #995
Changelog!
See #996

chore(release): Changelog

---

docs/Auth-with-Ionic3-Angular4.md

According to the code above, the hint "Ensure you've 'items' node in you database..." should say "Ensure you've 'cuisines' node in you...", becuase afDB.list('/cuisines') referes to that node, not '/items'.

Change 'items' to 'cuisines'

---

docs/4-querying-lists.md

- Issue number for this PR: #1005
- Test units included?: no, N/A
- e2e tests included?: no, N/A
- In a clean directory, `npm install`, `npm run build`, and `npm test` run successfully? no, N/A
Update to **Querying lists** docs to recommend `orderByChild` in favor of `orderByPriority`.
N/A

docs: recommend orderByChild in favor of orderByPriority

---

docs/1-install-and-setup.md
docs/6-angularfire-and-ionic-cli.md

- Issue number for this PR: #nnn (required) 
#1003
- Docs included?: (yes/no; required for all API/functional changes)  
Yes
No, N/A
- e2e tests included?: (yes/no; required for multi-function/multi-class changes) 
No, N/A
- In a clean directory, `npm install`, `npm run build`, and `npm test` run successfully? (yes/no; required) 
Yes
Fix for #1003. Added section an link to a specific Ionic/Ionic CLI installation and setup.
N/A

docs(ionic): add guide for setting up with ionic

---

docs/api-reference.md

Fixing spacing in an H1 so that Github's Markdown parser renders it appropriately.
- Issue number for this PR: n/a/
- Test units included?: n/a
- e2e tests included?: n/a
- In a clean directory, `npm install`, `npm run build`, and `npm test` run successfully? n/a
Fixing spacing in an H1 so that Github's Markdown parser renders it appropriately.
n/a

Fix H1 in Markdown

---

src/auth/auth.spec.ts

- Issue number for this PR: #1022
Unused console.logs

Remove console.log from the auth spec (closes #1022)

---

rollup-globals.js
src/angularfire2.spec.ts
src/app/firebase.app.module.ts

-  [x] Issue number for this PR: #518, #235
-  [ ] Docs included?: no
-  [x] Test units included?: yes
-  [ ] e2e tests included?: no
-  [x] In a clean directory, `npm install`, `npm run build`, and `npm test` run successfully?
This supports HMR by returning the existing app instance if it was already initialized. (See #518, #235)
Fixes errors such as
```
No App '[DEFAULT]' has been created - call App.initializeApp() (app/no-app).
```

fix(FirebaseApp): Return app if it exists

---

docs/Auth-with-Ionic3-Angular4.md

--v2 has been removed

---

docs/Auth-with-Ionic2.md
docs/Auth-with-Ionic3-Angular4.md

- Issue number for this PR: #1083
- Docs included?: Yes
- e2e tests included?: No
- In a clean directory, `npm install`, `npm run build`, and `npm test` run successfully? N/A
Fixing typo in docs
N/A

fixes #1083 - fix corodova typo in docs

---

.npmignore
.travis.yml
package.json
src/core/angularfire2.ts

Zone typings are breaking user app builds. Currently typing `Zone` to any until we have a better solution.

fix(typings): add ambient zone typings

---

docs/2-retrieving-data-as-objects.md

- Issue number for this PR: #1125
- Docs included?: Yes
- In a clean directory, `npm install`, `npm run build`, and `npm test` run successfully? Yes
Updating documentation regarding non-destructive behavior for `update()`.

Clarification of non-destructive updates

---

docs/Auth-with-Ionic3-Angular4.md

Fixes some minor spelling errors, makes punctuation more consistent throughout.
**Checklist**
- Docs included?: yes (is a doc update)
- Test units included?: none affected
- e2e tests included?: none affected
- In a clean directory, npm install, npm run build, and npm test run successfully? n/a
**Description**
Fixes some minor spelling errors, makes punctuation more consistent throughout.
**Code sample**
n/a

docs(Auth-with-Ionic3-Angular4) Fix Typos

---

README.md

Since Ionic 3.0 we call it just Ionic (like Angular) :)
PS: I will rewrite the tutorial later. I think one guide is enough for Ionic + Angular > 4.x

docs(readme): rename Ionic 2/3

---

docs/Auth-with-Ionic3-Angular4.md

AngularFireDatabase should be declared into providers section in app.module in order to be used by components
**Checklist**
-Issue number for this PR: n/a
-Docs included?: yes (is a doc update)
-Test units included?: none affected
-e2e tests included?: none affected
-In a clean directory, npm install, npm run build, and npm test run successfully? n/a
**Description**
In order to use AngularFireDatabase service you must first declare it in providers section in app.module.
Fixed the code, corrected and updated the instructions so that they reflect the code explained.

docs(Auth-with-Ionic3-Angular4) Fix Providers

---

docs/Auth-with-Ionic3-Angular4.md

Fix promise-polyfill instruction and make tutorial less verbose

docs(): Update Auth-with-Ionic3-Augular4.md

---

docs/firestore/querying-collections.md

I must have made that Stackblitz without logging into Github as I couldn't edit it today. I've linked a new one which I've updated with Cloud Firestore.

docs(afs): Fix the stackblitz link on the querying example

---

docs/firestore/collections.md

There was an issue with typing (I think) using the current way of returning a new object with the doc.id included. This method ensures that what gets returned is properly typed.
This method was used on two other examples (`.stateChanges()` and `auditTrail()`) so those were updated as well. I also found a handful of mis-named types (assume they were missed from copy/pasting) and so I updated those as well.
- Issue number for this PR: #1187 
- Test units included?: n/a

docs: fix object spread typing and mis-named variables

---

src/firestore/collection/changes.ts

- Docs included?: not required
- Test units included?: not required
Removed a `debugger` statement that in changes.ts that was causing the browser to pause in debug mode whenever the modified document change occurred.

fix(afs): remove debugger statement from collection/changes.ts

---

docs/install-and-setup.md

- Issue number for this PR: N/A
[Install-and-setup](https://github.com/angular/angularfire2/blob/master/docs/install-and-setup.md) had AngulaFireStoreModule twice in list, in step 6. I removed one of them.

docs(typo): firestore module was included twice in documentation

---

src/firestore/collection/changes.ts
src/firestore/collection/collection.spec.ts
tools/build.js

- Issue number for this PR: #1184
Per #1184 AFS is filtering empty sets from valueChanges(), this has been fixed.

fix(afs): Don't filter empty changes (allow for null set), closes #1184

---

docs/firestore/documents.md

docs(typo):misspelled word 'methods'

---

docs/version-5-upgrade.md

Problem with 'key' and '$key' in migration guide.
- Issue number for this PR: #nnn (required) 
Updating the migration guide, to correct a (possible) error: Problem with 'key' and '$key' in migration guide. Fix in docs for variable name consistency.

Problem with 'key' and '$key' in migration guide.

---

docs/rtdb/objects.md

typo corrected: use `payload` not `snapshot`

---

src/firestore/document/document.ts

- Issue number for this PR: #1245 
- Docs included?: Docs exist, but don't work quite as intended
Strongly typing the parameter requires that the object that's passed in is a complete match for the model. Normally though, you should be able to pass whatever you want to set and update (any number of fields in the model) and it should work.

Change doc.update() parameter type to Partial<T>

---

docs/rtdb/lists.md
docs/rtdb/objects.md

[Typo] retreive -> retrieve

---

src/firestore/public_api.ts

Closes #1249
All interface in `'./interfaces'` are already exposed by other API's so using `export *` isn't introducing anything new.

feat(afs): export interfaces

---

docs/firestore/collections.md

- Issue number for this PR: N/A
- In a clean directory, `npm install`, `npm run build`, and `npm test` run successfully?: yes
This is a simple spelling fix. Changes an instance of metod to method. Only this documentation was edited.
N/A

fixes spelling error. metod = method

---

src/firestore/document/document.ts

Add options parameter to document `set` method and pass that to `this.ref.set`. 
It looks like my editor removed extra whitespace on the file. What is the style guide rules for trailing whitespace?

Allow document set options. Fixes #1332

---

docs/rtdb/lists.md
docs/rtdb/objects.md

- Issue number for this PR: #1373 
- Test units included?: not needed, doc only change
- In a clean directory, `npm install`, `npm run build`, and `npm test` run successfully? not needed, doc only change
Per #1373 the docs needed to be updated to reflect the proper functionality of stateChanges() on RTDB as it functions different from Firestore. Also while making these changes I noticed objects.md still had some outdated information that referenced how pre 5.0 functioned. I wanted to clean this up with the current functionality.

Update RTDB docs to reflect 5.0 changes

---

docs/firestore/collections.md

There seem to be two unfinished paragraphs lingering in this documentation. This commit removes them.

Remove unfinished paragraphs from collections doc

---

src/firestore/enable-persistance-token.ts
src/firestore/firestore.module.ts
src/firestore/firestore.spec.ts
src/firestore/firestore.ts

- Issue number for this PR: #1206  (required)
- Docs included?: yes 
Fixing Error with Dependency Injection not being able to resolve all parameters in an Injectable class.
AngularFirestore is an Injectable class meaning its parameters must be resolvable via Dependency Injection.
Its current inability to do this, results in the warning:
```sh
Warning: Can't resolve all parameters for AngularFirestore in /XXXProjectPathXXX/node_modules/angularfire2/firestore/index.d.ts: ([object Object], ?). This will become an error in Angular v6.x
```
Using the injected Token allows the shouldEnablePersistence parameter to be resolvable via DI thus fixing the above warning! …

fix(afs): fix di warning

---

package.json
src/storage/observable/fromTask.ts
src/storage/ref.ts
src/storage/storage.spec.ts
src/storage/storage.ts
src/storage/task.ts

Addressing some issues found relating around `AngularFireUploadTask` promises.

fix(storage): task promise fixes

---

.travis.yml
karma.conf.js
tools/run-typings-test.js

* Attempting to go with ChromeHeadless for karma tests
* Seeing if going back to `yarn` for Travis works
* Only build PRs once
* Adding a sleep, seems to help some of the flakiness

Chrome headless & yarn for testing

---

.travis.yml

Caching yarn on Travis

---

src/firestore/firestore.spec.ts
src/firestore/firestore.ts

- Issue number for this PR: #1337 (required)
- Test units included?: yes)
Allows firestore collection and doc to be constructed from both references and string paths.
Do I need to add better tests? I was not sure how to get a reference easily, so I just took one from `afs`, which seems a bit backwards in a way.
Also not sure if there are any required documentation changes. Let me know in that case!
Changes the interfaces to: 
```typescript
collection<T>(pathOrRef: string | CollectionReference, queryFn?: QueryFn): AngularFirestoreCollection<T>
doc<T>(pathOrRef: string | DocumentReference): AngularFirestoreDocument<T>
```

feat(firestore): allow collection and doc from ref

---

docs/storage/storage.md

Tiny typo in documentation
- Issue number for this PR: #1504
- In a clean directory, `yarn install`, `yarn test` run successfully?: yes
Just solved a tiny event binding typo in the storage.md file (topic: **AngularFireStorage**).

Fixed typo in storage.md - (on change) should be (change)

---

.travis.yml

Tests on PRs are red right now, becuase Firebase JS SDK is breaking. Fix how were testing. 
A) if it's a PR, use the lockfile
B) if it's master, upgrade (this is so we're alerted of failure on Cron every night)
C) add a canary test, which is allowed to fail. I will work with the JS SDK team to make sure they're alerted of these failures
https://github.com/firebase/firebase-js-sdk/issues/605

Adding a test matrix and using the lockfile

---

src/storage/ref.ts
src/storage/storage.ts

fix(storage): Add our zone wrappers for download url and meta-data

---

package.json
src/auth/auth.ts
src/core/angularfire2.ts
src/database-deprecated/firebase_list_factory.ts
src/database-deprecated/firebase_object_factory.ts
src/database/database.spec.ts
src/database/database.ts
src/database/list/audit-trail.ts
src/database/list/create-reference.ts
src/database/list/state-changes.ts
src/database/object/create-reference.ts
src/database/observable/fromRef.ts
src/firestore/collection/collection.ts
src/firestore/firestore.ts
src/storage/storage.ts
tools/build.js
yarn.lock

- Issue number for this PR: #1583
Cleaning up some of the zone changes; further refactor is needed. Should fix change detection though.
I've published this PR as `5.0.0-rc.7.1-next` / `angularfire2@next`.

fix(): Fixing Zone.js issues

---

src/core/angularfire2.ts

- Issue number for this PR: #1597  (required)
- Docs included?: no (yes/no; required for all API/functional changes) 
- In a clean directory, `yarn install`, `yarn test` run successfully? yes (yes/no; required)
Should only `import {} from 'zone.js'` to import typing, but not import `zone.js` again, otherwise it will report `Zone is already loaded` error.
@jamesdaniels , please review, thank you.

fix(core): only import typing from zone.js

---

src/core/angularfire2.spec.ts
src/core/angularfire2.ts

Updates core to rxjs pipeable operators

(core) Update to rxjs pipeable operators

---

src/firestore/collection/changes.ts
src/firestore/collection/collection.spec.ts
src/firestore/collection/collection.ts
src/firestore/document/document.spec.ts
src/firestore/document/document.ts
src/firestore/firestore.spec.ts
src/firestore/firestore.ts
src/firestore/interfaces.ts
src/firestore/observable/fromRef.ts

Updates firstore to rxjs pipeable operators

(firestore) Update to rxjs pipeable operators

---

src/database/interfaces.ts
src/database/list/audit-trail.spec.ts
src/database/list/audit-trail.ts
src/database/list/changes.spec.ts
src/database/list/changes.ts
src/database/list/create-reference.ts
src/database/list/snapshot-changes.spec.ts
src/database/list/snapshot-changes.ts
src/database/list/state-changes.spec.ts
src/database/list/state-changes.ts
src/database/object/create-reference.ts
src/database/object/snapshot-changes.ts
src/database/observable/fromRef.spec.ts
src/database/observable/fromRef.ts
src/database/utils.ts

Updates database to rxjs pipeable operators

(database) Update to rxjs pipeable operators

---

src/auth/auth.spec.ts
src/auth/auth.ts
src/core/angularfire2.ts
src/core/firebase.app.module.ts
src/database-deprecated/database.ts
src/database/database.spec.ts
src/database/database.ts
src/firestore/firestore.spec.ts
src/firestore/firestore.ts
src/storage/storage.spec.ts
src/storage/storage.ts
test/ng-build/ng6/package.json
test/ng-build/ng6/src/app/app.module.ts
test/ng-build/ng6/yarn.lock

- Issue number for this PR: #1635
Turns out type guards cannot be used in decorators.
We'd like to keep `AngularFireModule.initializeApp` in step with the Firebase JS SDK's `initializeApp`, so I had to change the Injection Tokens yet again; fortunately these were not documented to begin with. Dropping `FirebaseAppConfigToken` and `FirebaseAppNameToken` in favor of a new `FirebaseNameOrConfigToken`.
This will allow `AngularFireModule.initializeApp` to be used with AOT, which we regressed on in RC.8.

fix(): allow initializeApp to be used with AOT

---

src/firestore/document/document.ts

Whoops! Thought I got this into RC 9 but I guess not. Sub-collections should default their type to `DocumentData` not `{}`.

fix(firestore): default sub-collections to DocumentData

---

CHANGELOG.md
package.json

chore(): 5.0.0-rc.9

---

CHANGELOG.md
package.json

chore(): rc.10

---

docs/ionic/authentication.md
docs/ionic/v3.md

authentication with ionic and firebase
- Issue number for this PR: [#1601](https://github.com/angular/angularfire2/issues/1601) [#1600 ](https://github.com/angular/angularfire2/issues/1600) [#1719](https://github.com/angular/angularfire2/issues/1719)  [#1733](https://github.com/angular/angularfire2/issues/1733)
Updating our documentation on Ionic Authentication. it work with google and facebook

docs(): authentication tutorial with ionic and rxjs compact for angularfire2  ^rc.10

---

src/core/firebase.app.module.ts
tools/build.js

While not optimal, this will fix the .filter for undefined issues while compiling for the server for now.
* Import the ESM version of `firebase/app`
* Ignore the type errors
* Drop `<any>` from config, as firebase is now an `any` itself
* Drop the trailing comma to allow building on older versions of Node (namely 6.x)

fix(core): Fix for the firebase/app export in Node

---

src/core/angularfire2.ts
src/messaging/messaging.module.ts
src/messaging/messaging.ts
src/messaging/observable/request-permission.ts
src/messaging/public_api.ts

FCM is not able to be included in node, it fails with a `self not defined` error. Rather than track this down and fix upstream, since FCM doesn't make sense server-side, let's jump the gun here and make the MessagingModule lazy.

feat(fcm): Lazy messaging, for compatibility with SSR

---

docs/firestore/documents.md

Description: Updating the documentation
for usage at the element-declarations in the class, otherwise error
- Issue number for this PR: #nnn (required) - 

add: export interface Item

---

src/core/angularfire2.ts
src/firestore/collection/collection.ts
src/firestore/document/document.ts

* `get()`'s options should be optional
* Add `get()` to docs
* `get()` should return to the Angular zone
* Since it's Promise-based and doesn't have side-effects, create and use a new simplified `runInZone` operator

fix(afs): optional get() options, get() for docs, and zone work

---

README.md
docs/functions/functions.md
docs/messaging/messaging.md

Don't merge until `@angular/fire` rename occurs.

docs(*): Document AngularFireFunctions and AngularFireMessaging

---

CHANGELOG.md
docs/messaging/messaging.md
package.json
src/core/package.json
src/messaging/messaging.ts

- Issue number for this PR: #1855 
* Changelogs and version bumps
* `.bind()` the messaging callbacks
* Another bug! `onTokenRefresh` doesn't actually return the token, just fires when you need to get it

Bind messaging

---

CHANGELOG.md
package.json
src/auth/auth.spec.ts
src/auth/auth.ts
src/core/angularfire2.spec.ts
src/core/firebase.app.module.ts
src/database-deprecated/firebase_object_observable.ts
src/database-deprecated/interfaces.ts
src/database/interfaces.ts
src/database/list/changes.spec.ts
src/database/list/remove.ts
src/database/list/snapshot-changes.spec.ts
src/database/list/state-changes.spec.ts
src/firestore/collection/collection.ts
src/firestore/document/document.ts
src/firestore/firestore.module.ts
src/firestore/firestore.spec.ts
src/firestore/firestore.ts
src/firestore/interfaces.ts
src/firestore/utils.spec.ts
src/functions/functions.spec.ts
src/functions/functions.ts
src/messaging/messaging.ts
src/storage/interfaces.ts
src/storage/observable/fromTask.ts
yarn.lock

- Issue number for this PR: #1907, #1874 (required)
- Docs included?: no, beta feature & don't have advanced config docs yet
* Allows for Angular 7 without peer dependency warnings
* Now requires Firebase ^5.5.
* Persistence settings can be passed in via the `enablePersistence` factory method or via the `PersistenceSettingsToken` injection token.
* Now that `firebase/app` is less broken, pull in many of the types from there.
* Allow configuration of Function region with the `FunctionsRegionToken` Injection Token
```ts
imports: [
AngularFirestoreModule.enablePersistence({experimentalTabSynchronization: true}),
AngularFireFunctionsModule
],
providers: [
{ provide: FunctionsRegionToken, …
```

5.1 release: support Firebase 5.5, multi-tab sync, function region selection, and Angular 7

---

docs/functions/functions.md
src/functions/functions.ts

- Issue number for this PR: #1945
- Docs included?: No
Added a FunctionsDefaultRegion, so the user does not need to add a FunctionsRegionToken to his ngModule.
I also edited the documentation to use the FunctionsRegionToken.
IMPORTANT: I added `FunctionsDefaultRegion` as constant directly int the functions.ts . If you manage those constants anywhere also or inside the class, please change it!

fix(functions): Set default functions region and add documentation - fix #1945

---

src/functions/functions.ts

- Issue number for this PR: #1945 (required)
I pulled in #1946, which is a fix for #1945 but in reading the code a bit more I realize the issue here is that we have to pass `undefined` if we want to trip the Firebase JS SDK default argument. Unfortunately an undefined optional injection comes through as `null` in Angular. 
This new fix is inline with the default argument I provide in [Database](https://github.com/angular/angularfire2/blob/master/src/database/database.ts#L24) and [Storage](https://github.com/angular/angularfire2/blob/master/src/storage/storage.ts#L33).
I prefer this as it's …

fix(functions): Better fix for Functions Region

---

docs/storage/storage.md

- Issue number for this PR: #1875
- Docs included?: Only changed docs
- Test units included?: No, just change to docs
Added short `StorageBucket` example to storage docs.

Add StorageBucket injection token to storage docs

---

src/auth/auth.ts
src/core/firebase.app.module.ts
src/database-deprecated/database.ts
src/database/database.ts
src/firestore/firestore.ts
src/functions/functions.ts
src/messaging/messaging.ts
src/storage/storage.ts

`@Optional()` injections are actually passed through as `null` (rather than `undefined`, if not present), this has lead to a couple bugs in the past. Just shoring all these up to avoid similar mistakes in the future.
No API change.

chore(): Shoring up @Optional types

---

src/firestore/firestore.ts
src/messaging/messaging.ts

Allow Firestore offline and messaging in non-server environments such as workers

---

package.json
src/core/collection.json
src/schematics/index.ts
src/schematics/ng-add.spec.ts
src/schematics/tsconfig.json

Set up builder/schematic in package.json

---

src/firestore/firestore.ts

Change the condition that determines whether timestampsInSnapshots setting is set to true.
This is done to order to comply with multiple digits minor versions of firebase sdk.
For example: version 5.10.0 is greater than 5.8.0
fixes #2050
- Issue number for this PR: #2050 
Fixes #2050 
Change the condition that determines whether timestampsInSnapshots setting is set to true.
This is done to order to comply with multiple digits minor versions of firebase sdk.
For example: version 5.10.0 is greater than 5.8.0

fix: change firestore default settings version comparison

---

package.json
src/root.spec.js
src/schematics/deploy/actions.spec.ts
src/schematics/deploy/actions.ts
src/schematics/deploy/builder.spec.ts
src/schematics/deploy/builder.ts
src/schematics/index.spec.ts
src/schematics/index.ts
src/schematics/interfaces.ts
src/schematics/ng-add.spec.ts
src/schematics/ng-add.ts
src/schematics/public_api.ts
src/schematics/tsconfig-build.json
src/schematics/tsconfig-esm.json
src/schematics/tsconfig-test.json
src/schematics/utils.ts

- Issue number for this PR: none
- Docs included?: no API changes
Introducing tests for `ng deploy firebase`.

test: add specs for ng deploy firebase

---

docs/deploy/getting-started.md

- Issue number for this PR: #nnn not applicable
Adding docs for the deployment schematics.

docs: add docs for the deployment capabilities

---

.travis.yml

**Node 12 has been cut, but we're not compatible yet.** Fall to `lts/*` (10.15, something or other?) to fix Travis builds.

chore(): Travis should use Node LTS

---

package.json
src/core/firebase.app.module.ts
yarn.lock

- Issue number for this PR: #2059
While giving us a bit more type safety in development, implementing `app.App` allows the Firebase JS SDK to break our builds in minor releases. Which has bit us more than once.
I do not believe this is worth keeping around any longer.
No API change.

fix(): FirebaseApp Class should not implement app.App

---

cloudbuild.yaml
package.json
src/database/list/audit-trail.ts
tools/build.sh
tools/release.sh
tools/test.sh
wrapper/package.json
yarn.lock

* Yarn upgrade, go with TypeScript 3.1.6 for development
* Drop the type on auditLog's scan, this can be implicit now and being explicit was angering TSC
* Adding a CI/CD process using Cloud Build, see [go/angularfire-releasing](http://go/angularfire-releasing)

chore(): Fix for Travis master and adding a CI/CD pipeline

---

docs/functions/functions.md
package.json
src/functions/functions.spec.ts
src/functions/functions.ts
yarn.lock

Allow AngularFireFunctions to point to the Cloud Functions Emulator. This increases minimum requirement of Firebase to 5.5.7.
Point callable Functions to the Cloud Function emulator by adding the  `FunctionsEmulatorOriginToken` to the `providers` section of your `NgModule`.
```ts
import { NgModule } from '@angular/core';
import { AngularFireFunctionsModule, FunctionsEmulatorOriginToken } from '@angular/fire/functions';
@NgModule({
imports: [
...
AngularFireFunctionsModule,
...
],
...
providers: [
{ provide: FunctionsEmulatorOriginToken, useValue: …
```

feat(functions): Allow configuration of Functions Emulator Origin

---

src/firestore/firestore.ts

This is a workaround to fix the Nodejs build - 
https://github.com/firebase/firebase-js-sdk/issues/1754#issuecomment-491566739
https://github.com/angular/angularfire2/issues/2071
The root cause is that firebase type definition is incompatible with the esm build. We will fix it in the next major version in firebase, but before that happens we will need this workaround.

fix: use default import for firebase

---

CONTRIBUTING.md

- Issue number for this PR: N/A
- update Contributing Guide for yarn
- remove out of date docs deployment instructions
N/A

docs(contributing): update for yarn

---

docs/functions/functions.md

docs(functions): avoid CORS preflight with hosting

---

docs/performance/getting-started.md

docs(performance): Adding information on polyfilling FID

---

CHANGELOG.md
package.json
src/core/package.json

- Issue number for this PR: #2094
- Docs included?: not needed
- Test units included?: covered by existing
The new peerDependencies included for the schematics aren't necessary to include in the published package and the peer warnings are confusing, especially for yarn users.
The dependencies on `fuzzy`, `inquirer`, and the `@angular-devkit/*` are taken care of if the developer uses `ng add @angular/fire` (4ed421c) and are only used in that step.
The `firebase-tools` dependency doesn't have to be expressed as a peer, as if you try to do `ng deploy` without `firebase-tools` installed you get a good error:
```
Error when trying to deploy: 
Cannot find module 'firebase-tools'
```

chore(): removing the new peers, unneeded and confusing to existing users

---

tools/build.sh
tools/release.sh

chore(build): we aren't prefixing tags with 'v'

---

.travis.yml

Currently node version for travis is LTS, which switched from 10 to 12 recently, hence all builds are failing because of node-gyp.
My understanding is that updating to firebase 7 would eventually allow us to switch back to LTS, but short term this should fix the build. 
cc #2221

fix(ci): Use node 10 to fix the build

---

src/schematics/deploy/builder.ts
src/schematics/utils.ts

Angular devkit paths are not interchangeable with Node FS paths.
Closes #2088

fix(schematics): fix issues with FS and Devkit Paths

---

src/auth/auth.ts

- Issue number for this PR: #2307 (required)
This fixes #2307 where `AngularFireAuth.authState` incorrectly uses `auth.onIdTokenChanged`.
None

fix(auth): use `onAuthStateChanged` for `authState`

---

.travis.yml
CHANGELOG.md
package.json
src/core/angularfire2.ts

I believe this to be the root cause of #2309, #2314, #2312.
This came up in the review of #2243 but neither my test applications or the test suite caught that it would cause any issues. I merged into 5.x series because I figured `fromRef` was deep enough in the codebase and dropping a `share()` wasn't a big deal.
I'm planning to drop this in a patch.
Demonstrating the break fix/here https://stackblitz.com/edit/angular-7kb1uf?file=src%2Fapp%2Fapp.component.ts

Removing the problematic share from the zone.js changes

---

docs/version-6-upgrade.md

(fix) typo fixed (i -> e)

---

src/auth-guard/auth-guard.ts

Fix auth guard timing to not cause issues with change detection and other issues on lazy loaded routes.
- Issue number for this PR: #2365 & #2367 (required)
I am fixing a bug caused by using lazy loaded modules on a full page refresh. 
See issues

Fix auth guard timing

---

docs/auth/router-guards.md

Update to documentation.
Add missing closing brace in code example

fix: missing closing brace in docs

---

docs/firestore/collections.md

- Issue number for this PR: #2461 (required)
- Docs included?: yes (yes/no; required for all API/functional changes) 
- In a clean directory, `yarn install`, `yarn test` run successfully? no (yes/no; required)
This pull request is to fix a documentation typo, on line 194 of ./docs/firestore/collections.md. The line is exporting an interface AccountDepositId but it is improperly named _AccountDepoistId_. This pull request fixes this typographical error.
Current State:
```typescript
export interface AccountDepoistId extends AccountDeposit { id: string; }
```
State with Pull Request Merged:
```typescript
export interface AccountDepositId extends AccountDeposit { id: string; }
```

Fixed typo in collections.md line 194

---

docs/functions/functions.md

The default port in the firebase emulator for functions is 5001, not 5005
Documentation fix for emulated function

Fix functions emulator origin url

---

CONTRIBUTING.md
ISSUE_TEMPLATE.md
README.md

Currently ISSUE_TEMPLATE offers to use plankr/jsfiddle, but it seems like it's too much extra effort to set things up.
Using StackBlitz template should help.

chore(): Use Stackblitz template in ISSUE_TEMPLATE.md

---

docs/analytics/getting-started.md

- Issue number for this PR: #2510 (required)
- Docs included?: yes (yes/no; required for all API/functional changes) 
- In a clean directory, `yarn install`, `yarn test` run successfully? no (yes/no; required)
This pull request fixes a documentation typo, in line 125 of _./docs/analytics/getting-started.md_. The word _Analytics_ is misspelled as _Analtyics_.
N/A

Corrects typo in analytics/getting-started.md line 125

---

docs/functions/functions.md

the DI token for functions origin was renamed, this PR fixes the import in docs example

fix import in functions docs

---

src/auth-guard/auth-guard.ts

Fixes: #2494
Signed-off-by: William Sedlacek <wsedlacekc@gmail.com>
- Issue number for this PR: #2494
- Docs included?: No
Adds explicit return types to these helper functions which makes them compatible with `canActivate()` while using strict mode in TypeScript
`hasCustomClaim()`, `redirectUnauthorizedTo()` and `redirectLoggedInTo()` will now all return `AuthPipe` explicitly rather the the inferred type.

fix(auth-guard):  Explicit return types

---

src/analytics/analytics.ts

Change arrow function to a normal function to use the arguments object as described in the gtag documentation. That way, analytics sends data back to Google again.
Fixes #2505
- Issue number for this PR: #2505 
Since updating to version 6.0.1, analytics no longer sends data to the Firebase Console. Analyzing and debugging this lib I realized that the code that defines a custom datalayer in gtag has been changed from a normal function to an arrow function.
After some research I learned that 'arguments' is not an array, it is actually an object that behaves like an array and contains more information besides indexes. 
I'm not sure what the analytics need for this …

fix(analytics): Fix custom data layer function

---

src/analytics/analytics.ts

Adding a warning in the code so no one can turn the gtag function into an arrow function.
PR #2594
- Issue number for this PR: #2594
As requested in the other PR by @Splaktar  I inserted a warning in the code to alert anyone who is going to make changes in analytics about not turning the function into an arrow function

refactor(analytics): Add warning in the code

---

src/schematics/deploy/actions.jasmine.ts
src/schematics/deploy/actions.ts
src/schematics/deploy/builder.ts

Depending on the configuration and initialization of the builder runtime, there may not be a workspace file or the raw values within the workspace file may not represent the final values used by a builder.  To support cases where inspection of builder target options is needed, the builder runtime provides a utility function (`getTargetOptions`) within the context object passed to each builder.  This utility function is now used within the deploy builder to access builder target options.  Also, as a result of these changes, usage of the experimental workspace API was removed.  This experimental API is no longer present as of Angular v11.

fix(deploy): remove direct workspace access

---

src/schematics/interfaces.ts
src/schematics/ng-add-ssr.ts
src/schematics/ng-add-static.ts
src/schematics/ng-add.ts
src/schematics/utils.ts

This change removes usage of the experimental workspace API.  Only two types were used within the schematics. The experimental workspace API is no longer present as of Angular v11.

fix(schematics): remove experimental workspace API type usage

---

src/firestore/collection/collection.ts

- Issue number for this PR: #2639
- In a clean directory, `yarn install`, `yarn test` run successfully? no
Updated doc function generic return type to inherit type from class generic
Without this change defining type on `collection` function call does not pass it to `doc` function call:
`db.collection<Location>('locations').doc('someid').valueChanges(); // Returns Observable<unknown>`
`db.collection<Location>('locations').doc<Location>('someid').valueChanges(); // Returns Observable<Location>`
With this PR calling `collection` function with type will pass it to `doc` function call. 
`db.collection<Location>('locations').doc('someid').valueChanges(); // Returns Observable<Location>`
`db.collection<Location>('locations').doc<Location>('someid') …

Inherit doc return type from class

---

docs/install-and-setup.md

- Docs included?: (yes) 
- Test units included?: (yes) 
- In a clean directory, `yarn install`, `yarn test` run successfully? (yes)
Dear angularfire community.
I was installing angularfire into my angular 9 project and i got the error
`Installations: Missing App configuration value: "appId" (installations/missing-app-config-values). ; Zone: <root> ; Task: Promise.then ; Value: FirebaseError: Installations: Missing App configuration value: "appId" `
After adding the appId and measurementId into `/src/environments/environment.ts` the error went away and it started working. So i wanted to help others by doing this PR and added the missing information to the install-and-setup.md.
I know that this PR has no Issue number, but it hope it's okay :)
This …

Added the missing appId and measurementId in install-and-setup.md

---

docs/deploy/getting-started.md
sample/angular.json
src/schematics/deploy/actions.ts
src/schematics/deploy/builder.ts
src/schematics/deploy/functions-templates.ts
src/schematics/deploy/schema.json
src/schematics/interfaces.ts
test/ng-build/ng9/src/app/app.component.spec.ts

feat(deploy): More deploy options

---

CHANGELOG.md
sample/src/app/app-routing.module.ts
sample/src/app/app.component.ts
sample/src/app/app.module.ts
sample/src/app/protected-lazy/protected-lazy-routing.module.ts
sample/src/app/protected-lazy/protected-lazy.component.html
sample/src/app/protected-lazy/protected-lazy.component.spec.ts
sample/src/app/protected-lazy/protected-lazy.component.ts
sample/src/app/protected-lazy/protected-lazy.module.ts
sample/src/app/protected/protected.component.html
sample/src/app/protected/protected.component.spec.ts
sample/src/app/protected/protected.component.ts
sample/src/app/secondary/secondary.component.html
sample/src/app/secondary/secondary.component.spec.ts
sample/src/app/secondary/secondary.component.ts
src/analytics/analytics.service.ts
src/analytics/analytics.ts

* Better handle lazy routes
* Better handle nested routes
* Better handle nested & lazy routes
* Handle multiple outlets correctly
* Handle multiple outlets that share the same lazy components (this was tricky)
* NO LONGER USING INTERNAL APIS OR REQUIRING ANNOTATIONS!!!! 🎉 😄 
* `APP_NAME` and `APP_VERSION` should be working now...
* `AngularFireAnalytics` now gets it's `measurementId` from Analytics rather than your config, there's an edge case where this can change out from underneath you, which the JS SDK handles
* Got `DEBUG_MODE` working again

feat(analytics): Bunch of analytics & screen tracking improvements

---

README.md
sample/package.json
sample/src/app/app.module.ts
sample/src/app/auth/auth.component.ts
sample/src/app/firestore-offline/firestore-offline.component.spec.ts
sample/src/app/firestore-offline/firestore-offline.component.ts
sample/src/app/firestore-offline/firestore-offline.module.ts
sample/src/app/home/home.component.ts
sample/yarn.lock
src/analytics/analytics.module.ts
src/analytics/analytics.ts
src/analytics/public_api.ts
src/analytics/screen-tracking.service.ts
src/analytics/user-tracking.service.ts
src/auth/auth.ts
src/core/angularfire2.ts
src/core/firebase.app.module.ts
src/database/database.spec.ts
src/database/database.ts
src/firestore/firestore.ts
src/functions/functions.ts
src/messaging/messaging.ts
src/performance/performance.ts
src/remote-config/remote-config.ts
src/storage/storage.ts

* Adding global instance caches to the modules, so they don't freak out when HMR is enabled (#2655). This takes on `globalThis` as a needed polyfill for many environments.
* If injected settings for modules are changed after they are initialized you will receive a warning and the prior instance will be returned (ignoring the changes), this is especially important for HMR. If HMR is detected there will be an additional warning suggesting they do a full reload to see the changes.
* Added a polyfill table and notes about why we version like we do
* Adding more convoluted stuff to my sample app to flex AngularFire
* Internal cleanup on AngularFireAnalytics
* AngularFireAnalytics will now wait for UserTrackingService to detect the user before sending the screen_view event, if …

Adding global caches to survive/warn on HMR, cleanup, etc.

---

sample/src/app/app.module.ts
src/core/firebase.app.module.ts

It turns out that in sufficiently complex use-cases (e.g, not my sample app) ngc / webpack has now (6.1) decided that our injectables (such as AngularFirestore) can be duplicated... presumably because of something, something, tree-shaking magic formulas.
While I was aware this could happen and intended my instance cache to cover this and the HMR use-case, I had a bug in my fetch logic which would try to reinitialize the SDK instance even when the settings hadn't changed. Whoops. Explains why this wasn't working for HMR users as intended either.

fix(core): fix the instance cache logic, closes #2666

---

src/firestore/collection/collection.ts

Merge conflict during the war of the release candidates, accidentally wiped out #2640. Bring it back!

fix(afs): fix regression keeping one from overriding collection.doc type

---

sample/src/app/auth/auth.component.ts
sample/yarn.lock
src/analytics/user-tracking.service.ts
src/auth-guard/auth-guard.ts
src/auth/auth.ts

I added a `shareReplay` as a temporary work around to Zone.js issues in Firebase v8 with auth, I did not intent to ship this. I've since found work-arounds.
* Only `keepUnstableUntilFirst` on `redirectResult`, `shareReplay` it
* Remove shareReplay which causes issues when loading/checking auth lazily
* Move guards over to `.user` so token changes will be evaluated
* Upgrade the node modules in sample
Addresses #2681

fix(auth): removed the shareReplay from auth and addressed Zone.js issues

---

src/firestore/observable/fromRef.ts

Document snapshots will now come with `added`, `removed`, and `modified` types as documented, rather than simply `value`.

fix(afs): fix type in DocumentActions

---

sample/src/app/app.component.ts
src/firestore/collection/changes.ts
src/firestore/collection/collection.ts

* `stateChanges` and `auditLog` will show metadata updates correctly now, rather than just `[]`
* `snapshotChanges` uses same codepath as `stateChanges` and `auditLog`
* filter out empty arrays from `stateChanges`, even when no options provided

fix(afs): stateChanges and auditLog correctly emit metadata changes

---

src/core/firebase.app.module.ts

If we're having trouble comparing the objects (just using JSON.stringify now) don't hard-fail, just skip the warning. This was meant as just guardrails for those lazy-loading or HMR rather than diehard functionality.
Closes #2672

fix(core): try/catch the HMR/DI warning

---

src/storage/observable/fromTask.ts
src/storage/storage.spec.ts

Ugh this was still broken. `task.snapshot` and `task.on('state_changed', ...)` never return the "last" snapshot, have to use the promise form of task to get at it.
* Works on tasks that are already running
* Now emits a final success snapshot before completion
* ~~Emits a filterable canceled or error snapshot prior to a throw~~ There appears to be a JS SDK bug blocking this 😢 in theory it should work in a future release
* Added tests for canceling, pausing, and resuming

fix(storage): snapshotChanges should return a success snapshot

---

docs/auth/getting-started.md

- Issue number for this PR: #2663
Updating the Auth documentation with the usage of DI tokens 🚀

docs(auth): provide auth DI tokens documentation

---

src/auth/auth.spec.ts
src/auth/auth.ts

- Issue number for this PR: #2826 
Instead of assigning to the auth `settings` readonly object, assign directly the property `appVerificationDisabledForTesting`.

fix: auth settings setter instead of ovewriting readonly object

---

src/schematics/deploy/actions.jasmine.ts
src/schematics/deploy/actions.ts
src/schematics/interfaces.ts
src/schematics/setup/index.ts
src/schematics/setup/prompts.ts

Adding multi-user support to `ng add` and `ng deploy`

Adding multi-user support.

---

samples/advanced/angular.json
samples/advanced/package.json
samples/advanced/src/app/app.browser.module.ts
samples/advanced/src/app/app.server.module.ts
samples/advanced/src/app/database/lazyDatabase.ts
samples/advanced/src/app/emulators.prod.ts
samples/advanced/src/app/emulators.ts
samples/advanced/src/app/functions/lazyFunctions.ts
samples/advanced/src/app/getFirestore.ts
samples/advanced/src/app/storage/lazyStorage.ts
samples/advanced/yarn.lock
src/core.ts
src/schematics/deploy/actions.ts
src/schematics/ng-add.jasmine.ts
src/schematics/setup/ssr.ts
src/schematics/setup/static.ts

* Support multiple package managers on ng deploy, #2841
* Don't cache ngsw, #2259
* Got rid os AppCheck debug token on Node, opted for a better pattern in `samples/advanced`
* Added a new pattern for connecting the emulators in `samples/advanced`

Various improvements

---

src/schematics/ng-add.jasmine.ts
src/schematics/setup/index.ts

- Issue number for this PR: #3052
Closes #3052

fix(schematics): ng-add should pass if sourceRoot is relative to workspace root

---

docs/auth/getting-started.md

/compat missing from firebase import (#2917)

---

src/schematics/deploy/schema.json

Use `oneOf` instead of `"type": ["a", "b"]` to fix the `ng deploy` command.
Currently, running `ng deploy` with the `@angular/fire:deploy` builder results in the following error:
```
Property 'ssr' does not match the schema.
{
"type": [
"boolean",
"string"
],
"description": "Should we attempt to deploy the function to Cloud Functions (true or 'cloud-functions') / Cloud Run ('cloud-run') or just Hosting (false)"
}'
```
Running the same command with the proposed changes results in a successful deploy.
- Issue number for this PR: #3074

Fix properties in deploy schema that require oneOf

---

src/zones.ts

- Issue number for this PR: #3126 
- In a clean directory, `yarn install`, `yarn test` run successfully?: yes
- Define a `_arguments` variable and copy values of `arguments` into that.
- Avoid to direct referring to `arguments` in arrow functions

fix(core): avoid referring to arguments in arrow functions

---

src/compat/proxy.ts

Typescript 4.5 changed how inference with extends works, A) don't use `Function` as a type as that's a foot gun B) create a `ReturnTypeOrNever`/`ParametersOrNever` utility types to handle the inference changes. #3090 #3088

Fix for Typescript 4.5 inference breaks in the PromiseProxy

---

src/schematics/setup/prompts.ts

Fix the the ng add console freeze. #3145 #3121, [firebase-tools#4118](https://github.com/firebase/firebase-tools/issues/4118)
My first thought is that inquirer-autocomplete is broken... but while experimenting, I found that places in the code that had an autocomplete and were waiting on a pending firebase-tools call were locking up but those that prompted with an already resolved firebase-tools call were not... my suspicion is either something is up with the pinned version of inquirer, inquirer is conflicting with ora (`preparing list of ***...`), or how firebase-tools is loading inquirer when it's called (something, something, race condition). 
Either way, this is a high priority issue and this seems to fix it. :shipit:

Fix for the ng add console lock up

---

src/app/app.module.ts
src/auth/auth.module.ts
src/database/database.module.ts
src/functions/functions.module.ts
src/messaging/messaging.module.ts
src/performance/performance.module.ts
src/remote-config/remote-config.module.ts
src/storage/storage.module.ts

- Issue number for this PR: #3086
Adding missing typings/signature to existing functions. Writeup is available in #3086.

fix: added missing injector input signatures

---

.github/workflows/test.yml
README.md
package.json
src/package.json

Fix #3290
We need to bump major soon and drop the older Angular versions, the matrix test is getting a bit difficult to manage w/so many variants.
* Drop ng12 from the tests, JS SDK (typescript) broke, not work hunting for a good version IMO
* Skip prerender test on ng13, broken not worth hunting the flake IMO
* Add ng15 to the matrix, add upgrade to ng14 step
* Bump the version
* Add ng15 to the acceptable peers
* Add to README
* Contrib tests are failing on newer Node, we should look into but not block merging and cutting

Mark compatibility with ng 15 peer

---

docs/auth.md

- Issue number for this PR: #3373
Updated the docs for auth page for fixing typos and removed the extra "the" in the file

Fixed typos in docs/auth

---

docs/app-check.md

- Issue number for this PR: #3377
Documentation update: remove unsupported function from appcheck example

fix: remove unsupported function from appcheck example

---

src/analytics/analytics.module.ts
src/analytics/is-analytics-supported-factory.ts
src/analytics/overrides.ts
src/core.ts
src/messaging/is-messaging-supported-factory.ts
src/messaging/messaging.module.ts
src/messaging/overrides.ts
src/remote-config/is-remote-config-supported-factory.ts
src/remote-config/overrides.ts
src/remote-config/remote-config.module.ts

- Issue number for this PR: #3075 
`@angular/fire` core package always import these packages
- firebase/remote-config
- firebase/messaging
- firebase/analytics which increase the total bundle size for any application using `@angular/fire`

fix: Bundle includes unused firebase modules

---

README.md

Using the current code example, I am getting an error message Typescript error message like: 
```
Type 'Observable<(DocumentData | (DocumentData & { .... }))[]>' is not assignable to type 'Observable<Item[]>'.
```
This change also makes this code example more consistent with the current example in [firestore.md](https://github.com/angular/angularfire/blob/5793d6f3a15aa61660af75ab361c534cde9b73df/docs/firestore.md?plain=1#L91)
- Issue number for this PR: none. 
- Docs included?: yes.
- In a clean directory, `yarn install`, `yarn test` run successfully? yes.

Cast collectionData to avoid TS errors

---

docs/compat/firestore/collections.md
docs/compat/firestore/querying-collections.md
site/src/firestore/collections.md

- Issue number for this PR: #3408 (https://github.com/angular/angularfire/issues/3408)
- Docs included?:  No
- Test units included?:  No
- In a clean directory, `yarn install`, `yarn test` run successfully?  Yes

docs: update firestore query api link and collection reference link(#3408)

---

docs/messaging.md

Noticed that there was little documentation here, it took our team ~4 hours to find enough examples online to make it work, so we figured that we would update this.

Updating the Cloud Messaging docs for Angular Fire modular

---

site/src/get-started/quick-start.md

No longer need importProvidersFrom

---

src/schematics/setup/index.ts
src/schematics/utils.ts

ng-add providers

---

docs/analytics.md
docs/app-check.md
docs/database.md
docs/firestore.md
docs/functions.md
docs/performance.md
docs/remote-config.md
docs/storage.md

Doc changes

---

docs/auth.md

FirebaseServerApp documentation

---

README.md
docs/vertexai.md

VertexAI docs

---

docs/install-and-setup.md

- Issue number for this PR: Fixes #3571 
- Docs included?: **yes** 
- Test units included?: **no, N/A**
- In a clean directory, **N/A**
An update to `docs/install-and-setup.md` to align with the latest app sources when creating a new Angular project. The previous example used @ngFor which has been replaced with @for. Additionally the example requires that the component imports `AsyncPipe`.
N/A

Update Firestore example to use @for and AsyncPipe

---

src/zones.ts

This change will noop the zone wrapper when outside the injector context, addressing feedback in #3573

Allow use of zone wrappers outside injection context

---

src/auth/firebase.ts
src/zones.ts
tools/build.ts

* Zone wrapper noops for our other helpers
* Add a warning / error on potential Zone / hydration issues
* Pass injection context to `zoneWrapFn` 
* Pass injection context into the Promise wrapper
* `beforeAuthStateChanged` should not block

Adding more injector safety

---

src/compat/auth/auth.ts
src/compat/database/database.spec.ts
src/compat/database/database.ts
src/compat/database/list/create-reference.ts
src/compat/database/object/create-reference.ts
src/compat/firestore/collection-group/collection-group.ts
src/compat/firestore/collection/collection.ts
src/compat/firestore/document/document.ts
src/compat/firestore/firestore.ts
src/compat/remote-config/remote-config.ts
src/compat/storage/ref.ts
src/compat/storage/storage.ts

- Issue number for this PR: #3594
Fix compat api methods to work with the updates from #3586.
No change to the API usage.

fix(compat): correct injectors to fix issue with compat API on v19

---

docs/zones.md
src/zones.ts

* Switch to warnings for lack of injection context, errors were stressin folk
* Start of a zone wrapper doc

Zone docs and switch to warnings

---

package-lock.json
package.json
src/schematics/deploy/actions.jasmine.ts
src/schematics/interfaces.ts
src/schematics/setup/index.ts
src/schematics/utils.ts

Automatically set up Data Connect provider:
```
provideDataConnectQuery(() => getDataConnect(connectorConfig)), provideTanStack(new QueryClient())
```

Added data connect to schematics

---

.github/workflows/test.yml
package.json

Bump action, bump minor
